export enum TileStyle {
  STRAIGHT   = '/assets/images/tile-straight.png',
  CORNER     = '/assets/images/tile-corner.png',
  EMPTY      = '/assets/images/tile-bl.png.png',
  BAT        = '/assets/images/tile-bat.png',
  BUG        = '/assets/images/tile-bug.png',
  DRAGON     = '/assets/images/tile-dragon.png',
  FLY_THING  = '/assets/images/tile-fly-thing.png',
  GHOST      = '/assets/images/tile-ghost.png',
  GHOST_UGLY = '/assets/images/tile-ghost-ugly.png',
  OWL        = '/assets/images/tile-owl.png',
  MOUSE      = '/assets/images/tile-mouse.png',
  SALAMANDER = '/assets/images/tile-salamander.png',
  SPIDER     = '/assets/images/tile-spider.png',
  UGLY_ASS   = '/assets/images/tile-ugly-ass.png',
  WITCH      = '/assets/images/tile-witch.png',
}
